name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build Windows Mod
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Geode
        uses: geode-sdk/setup-geode@v1

      - name: Build Mod
        run: geode build --platform win

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: build/*.geode
